### ISSUE TITLE
Reuse terms in other OBO Foundry ontologies

### ISSUE THREAD

**Issue by zhengj2007** [scdodev/scdo-ontology#18]
[VEuPathDB ontology](https://github.com/VEuPathDB-ontology/VEuPathDB-ontology) is planning to reuse a SCDO term, [Sickling Test](http://purl.obolibrary.org/obo/SCDO_0001068). However, we found the hierarchy of SCDO does not consistent with other OBO Foundry ontologies we used and it does not reuse terms in other ontologies either. For example, [SCDO_0000133](http://purl.obolibrary.org/obo/SCDO_0000133) 'Blood Test' that is available on OBI, [OBI_0003040](http://purl.obolibrary.org/obo/OBI_0003040) 'blood assay'

The issues are also mentioned in the SCDO new ontology request:
https://github.com/OBOFoundry/OBOFoundry.github.io/issues/392

We would like to see the improvement of SCDO and allow us to make sure we use the SCDO term correctly in the VEuPathDB ontology.  Thanks!

**Comment by scdodev** [comment]
Thank you for the feedback, and apologies for taking so long to respond!

The SCDO does indeed reuse terms from other OBO ontologies, as SCDO curators deem appropriate.
In places where our hierarchy is different from other ontologies, this may be because our ontology is more comprehensive in that area, or because we do not agree with the hierarchy used by those ontologies, or that it does not serve our ontology's purpose. This sometimes happens if the other ontology is more general and has not been developed with the relevant clinical expertise, or has a very different purpose from ours.
Having said that, we are open to suggestions if our positioning of a term does not make sense.

You are welcome to reuse our "Sickling Test" term, which we have placed in the SCDO hierarchy in a way that makes sense in the SCD field and that serves the purpose of the SCDO.

We found the "Sickling Test" term in SNOMED is problematic in terms of its placement and its definition.
You can see our comment on this term for more information on that.
Its placement in other OBO ontologies was also not helpful for us.

We chose to use the definition for Blood Test that MESH uses, which we have referenced as our source.
When we started the SCDO we were not aware of the need for reusing OBO Foundry ontology terms and thus sourced our terms more widely, based purely on usefulness and relevance.
MESH is not an OBO ontology and thus ROBOT is not replacing our terms' url with that of the MESH term.
Maybe one day we will be able to spend time changing our definition source terms to relevant OBO Foundry ones where relevant, but for now we are not able to do that.
If OBI added "Blood Test" as a synonym for their "Blood Assay" term, our term would at least map to theirs in BioPortal.
Perhaps you could ask them to do that?

The SCDO developer is constantly working on improving the SCDO, so hopefully the next release will be more to your standard :)
